### ISSUE TITLE
[Mod]: 

### ISSUE THREAD

**Issue by JiMKesa** [KSP-CKAN/KSP2-NetKAN#64] opened 2023-07-01 21:26 UTC
### Mod Name

Kesa

### Author(s)

JiMKesa

### License

MIT

### Homepage link

https://kesaspace.blogspot.com/p/kesa-ksp2-mod.html

### Download link

https://spacedock.info/mod/3409/Kesa

**Comment by HebaruSan** [comment] 2023-07-02 18:26
Duplicate of #60

**Closed by HebaruSan** 2023-07-02 18:26 UTC
